### ISSUE TITLE
字型不對

### ISSUE THREAD

**Issue by vincicat** [ShawTim/ifc-roof#2]
參考 https://twitter.com/wenli/status/960782384521035776/photo/1

**Comment by ShawTim** [comment]
呢個應該算係known issue黎。
係搵到真正個font之前，暫時既work around就係將原圖所有數字執走佢，然後自己用自己font再render，令user無咁覺個字型唔同 (因為無得比較)。

但而家問題有二︰

1) 狗牙。現代font實在render得太smooth了；
2) browser support/consistency

我覺得只要解決好呢兩個問題，字型似唔似原圖都無所謂了。除非user將原圖並排黎對，否則根本唔知有分別...
